#!/usr/bin/env python3
"""Generate src/thermocouple_its90/_data.py from data/its90.json.

The JSON is the canonical dataset, machine-parsed from the NIST ITS-90
database files; this script freezes it into an importable module so the
installed package needs no file IO and no JSON parse at import time.
Run from the repository root:

    python codegen/gen_data.py

The test suite fails if the generated module drifts from the JSON.
"""

from __future__ import annotations

import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parents[1]
SRC = ROOT / "data" / "its90.json"
DST = ROOT / "src" / "thermocouple_its90" / "_data.py"

HEADER = '''"""GENERATED by codegen/gen_data.py from data/its90.json. DO NOT EDIT.

Coefficients of the ITS-90 thermocouple reference functions and inverse
polynomials, machine-parsed from the NIST ITS-90 Thermocouple Database
(SRD 60), which reproduces NIST Monograph 175, a United States government
publication not subject to copyright. Regenerate with:

    python codegen/gen_data.py
"""

'''


def main() -> None:
    data = json.loads(SRC.read_text(encoding="utf-8"))
    lines = [HEADER]
    lines.append(f"DATA_SOURCE = {json.dumps(data['source'])}\n")
    lines.append(f"DATA_FETCHED_UTC = {json.dumps(data.get('fetched_utc', ''))}\n")
    lines.append(f"LIBRARY_DATA_VERSION = {json.dumps(data.get('data_version', '1'))}\n")
    lines.append("\nTYPES = ")
    lines.append(repr(data["types"]))
    lines.append("\n")
    DST.write_text("".join(lines), encoding="utf-8")
    print(f"wrote {DST} ({DST.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
